This is notebook 2 for data cleaning, manipulation, and merging the four web-scraped files to form two datasets (primary and secondary), then clean, merge, and form a single final dataset.

## 2. Data Cleaning and Manipulation

### 1. Data Cleaning and Manipulation on Basic Stats, Advanced Stats and Country Data 

In this section, we will conduct data cleaning and manipulation on the Basic Stats, Advanced Stats, and Bio Data datasets, with the objective of merging them into an unified dataset for future use.

In [ ]:
# import pertinent libraries for data curation and manipulation
import pandas as pd
import numpy as np

# read datasets for primary dataset of base, advanced NBA Statistics and secondary NBA players' countries dataset
player_info_base = pd.read_csv('Player_Base_Statistics.csv')
player_info_advanced = pd.read_csv('Player_Advanced_Statistics.csv')
player_bio = pd.read_csv('Player_Country.csv')

In [ ]:
# change country names that not USA as international
player_bio.loc[player_bio["COUNTRY"] != "USA", "COUNTRY"] = "international"

In [ ]:
# Concatenate 'COUNTRY' column from player_bio into player_info_base
player_info_base = pd.concat([player_info_base, player_bio["COUNTRY"]], axis=1)

In [ ]:
# display all overlapping columns within player_info_advanced and drop them from player_info_advanced.
# we only keep columns PLAYER_ID','season_id as keys for merging later
overlapping_cols = [
    "PLAYER_NAME",
    "NICKNAME",
    "TEAM_ID",
    "TEAM_ABBREVIATION",
    "AGE",
    "GP",
    "W",
    "L",
    "W_PCT",
    "MIN",
    "FGM",
    "FGA",
    "FG_PCT",
    "GP_RANK",
    "W_RANK",
    "L_RANK",
    "W_PCT_RANK",
    "MIN_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
]

advanced_update = player_info_advanced.drop(overlapping_cols, axis=1)

In [ ]:
# merge player_info_base and advanced_update data into Merged_Stats
player_statistics_country = player_info_base.merge(
    advanced_update, on=["PLAYER_ID", "season_id"], how="inner"
)

# extract the start year of the season_id and convert it as integer type
player_statistics_country["season_id"] = player_statistics_country["season_id"].apply(
    lambda x: x[0:4]
)
player_statistics_country["season_id"] = player_statistics_country["season_id"].astype(
    int
)

Now that we have the merged dataset named 'player_statistics_country,' our next step involves manipulating the PLAYER_NAME column. This manipulation is necessary to ensure alignment in format between this dataset and the salary dataset. We will merge these datasets in the future based on player names and years, so it's important to harmonize the format.

In [ ]:
# eliminate special characters in PLAYER_NAME column
def clean_player_names(df, suffixes_to_remove):
    """The purpose of this function is to eliminate 
    the special characters in the PLAYER_NAME column.
    
    It accepts the following parameters:
        1) the dataframe to be cleaned
        2) a list of special characters to be removed
    """

    for suffix in suffixes_to_remove:
        df['PLAYER_NAME'] = df['PLAYER_NAME'].str.replace(suffix, "", regex=True)
    return df

suffixes_to_remove = ["\."," Jr"," Sr"," III"," II"," IV"]
clean_player_names(player_statistics_country, suffixes_to_remove)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,EFG_PCT_RANK,TS_PCT_RANK,USG_PCT_RANK,E_USG_PCT_RANK,E_PACE_RANK,PACE_RANK,sp_work_PACE_RANK,PIE_RANK,FGM_PG_RANK,FGA_PG_RANK
0,920,AC Green,A.C.,1610612742,DAL,33.0,83,23,60,0.277,...,203,213,404,406,348,372,372,135,191,199
1,243,Aaron McKie,Aaron,1610612765,DET,24.0,83,48,35,0.578,...,256,209,355,351,392,361,361,152,264,258
2,1425,Aaron Williams,Aaron,1610612763,VAN,25.0,33,4,29,0.121,...,17,26,289,280,390,362,362,81,202,253
3,768,Acie Earl,Acie,1610612749,MIL,27.0,47,14,33,0.298,...,400,389,94,91,231,173,173,332,304,289
4,228,Adam Keefe,Adam,1610612762,UTA,27.0,62,48,14,0.774,...,108,59,392,393,280,282,282,213,320,351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12841,1628380,Zach Collins,Zach,1610612759,SAS,25.0,63,20,43,0.317,...,164,172,130,134,47,86,86,132,132,153
12842,203897,Zach LaVine,Zach,1610612741,CHI,28.0,77,38,39,0.494,...,203,146,30,30,374,409,409,77,24,25
12843,1630192,Zeke Nnaji,Zeke,1610612743,DEN,22.0,53,34,19,0.642,...,83,105,362,358,495,472,472,373,337,377
12844,1630533,Ziaire Williams,Ziaire,1610612763,MEM,21.0,37,21,16,0.568,...,408,435,233,234,98,162,162,476,308,293


In [ ]:
# eliminate middle names in the PLAYER_NAME column if there is any
stats_first_name = (
    player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[0])
)
stats_last_name = (
    player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[-1])
)

player_statistics_country["PLAYER_NAME"] = stats_first_name + " " + stats_last_name

In [ ]:
# # eliminate middle names in the PLAYER_NAME column if there is any
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace("\.", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" Jr", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" Sr", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" III", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" II", "", regex = True)
# player_statistics_country["PLAYER_NAME"] = player_statistics_country["PLAYER_NAME"].str.replace(" IV", "", regex = True)


# stats_first_name = (
#     player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[0])
# )
# stats_last_name = (
#     player_statistics_country["PLAYER_NAME"].str.split(" ").apply(lambda x: x[-1])
# )

# player_statistics_country["PLAYER_NAME"] = stats_first_name + " " + stats_last_name

In [ ]:
#check shape of the merged player statistics and country dataframe
player_statistics_country.shape

(12846, 124)

We have successfully completed all the necessary cleaning, manipulation, and merging tasks on the merged statistics dataset 'player_statistics_country'. In the next section, we will work on salary dataset.

### 2. Data Cleaning and Manipulation on Salary Data

In [ ]:
import pandas as pd
import numpy as np

# read the tertiary salary dataset
df_sal = pd.read_csv("Player_Salary.csv")

In [ ]:
#observe for missing, NaN values, and data types
print(df_sal.head(20))
print(df_sal.sample(20))
df_sal.tail(20)

    Rank                                             Player Signed Age  Yrs  \
0      1  Stephen Curry  Point Guard | 2022-2025 (FA: 2026)         33    4   
1      2    Luka Doncic  Point Guard | 2022-2026 (FA: 2027)         22    5   
2      2     Trae Young  Point Guard | 2022-2026 (FA: 2027)         22    5   
3      4  Russell Westbrook  Point Guard | 2018-2022 (FA...         28    5   
4      5    LaMelo Ball  Point Guard | 2024-2028 (FA: 2029)         21    5   
5      5  Tyrese Haliburton  Point Guard | 2024-2028 (FA...         23    5   
6      7  Stephen Curry  Point Guard | 2017-2021 (FA: 2022)         29    5   
7      8      Ja Morant  Point Guard | 2023-2027 (FA: 2028)         22    5   
8      8  Darius Garland  Point Guard | 2023-2027 (FA: 2...         22    5   
9     10  Shai Gilgeous-Alexander  Point Guard | 2022-20...         23    5   
10    11  Ben Simmons  Point Guard | 2020-2024 (FA: 2025...         22    5   
11    12  Damian Lillard  Point Guard | 2021-2024 (F

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus
5591,933,Boris Diaw Center | 2011-2011 (FA: 2012) Ori...,28,1,"$345,248","$345,248",NaN
5592,934,Ryan Hollins Center | 2015-2015 (FA: 0),31,1,"$344,733","$344,733",NaN
5593,935,Ben Wallace Center | 1997-1997 (FA: 1998) Or...,-,1,"$326,700","$326,700",NaN
5594,936,Joe Kleine Center | 1997-1997 (FA: 1998) Ori...,34,1,"$272,250","$272,250",NaN
5595,937,Jason Collins Center | 2013-2013 (FA: 2014),26,1,"$271,669","$271,669",NaN
5596,938,Ryan Hollins Center | 2011-2011 (FA: 2012) O...,26,1,"$248,048","$248,048",NaN
5597,939,Ben Wallace Center | 1996-1996 (FA: 1997) Or...,-,1,"$247,500","$247,500",NaN
5598,940,Bernard James Center | 2014-2014 (FA: 2015),30,1,"$236,886","$236,886",NaN
5599,941,Larry Sanders Center | 2016-2017 (FA: 2018),28,1,"$207,722","$207,722",NaN
5600,942,Bill Wennington Center | 1993-1993 (FA: 1994)...,29,1,"$150,000","$150,000",NaN


In [ ]:
# look at the shape of the salary dataset
print("shape of df_sal dataframe: ", df_sal.shape, end="\n\n")

# look at data types and also determine existance of any NaN values in all the columns
for column in df_sal.columns:
    print(
        column,
        "- ",
        "Type: ",
        df_sal[column].dtypes,
        ", NaN Value: ",
        df_sal[column].isnull().any(),
    )

shape of df_sal dataframe:  (5611, 7)

Rank -  Type:  int64 , NaN Value:  False
Player -  Type:  object , NaN Value:  False
Signed Age -  Type:  object , NaN Value:  False
Yrs -  Type:  int64 , NaN Value:  False
Value -  Type:  object , NaN Value:  False
AAV -  Type:  object , NaN Value:  False
Sign Bonus -  Type:  object , NaN Value:  True


In [ ]:
# make copy of dataset for safety
df_salary = df_sal.copy()

In [ ]:
#check 'Player' column in df_salary
df_salary["Player"]

0       Stephen Curry  Point Guard | 2022-2025 (FA: 2026)
1         Luka Doncic  Point Guard | 2022-2026 (FA: 2027)
2          Trae Young  Point Guard | 2022-2026 (FA: 2027)
3       Russell Westbrook  Point Guard | 2018-2022 (FA...
4         LaMelo Ball  Point Guard | 2024-2028 (FA: 2029)
                              ...                        
5606    Dexter Pittman  Center | 2013-2013 (FA: 2014) ...
5607           Prince Ibeh  Center | 2016-2016 (FA: 2017)
5608    Christian Wood  Center | 2015-2015 (FA: 2016) ...
5609    Greg Stiemsma  Center | 2009-2009 (FA: 2010)  ...
5610           Jeff Foster  Center | 1999-2002 (FA: 2003)
Name: Player, Length: 5611, dtype: object

As we observe the data in the 'Player' column above, it contains information about the player's name, position, contract start year, contract end year, and free agent year. We will extract each of these data from the 'Player' column and allocate them to new columns.

In [ ]:
# extract data from the Player column and assign them to two new columns: names & positions
split_name_yr = df_salary["Player"].str.split("|")

name_position = split_name_yr.apply(lambda x: x[0])

names = name_position.str.split("  ").apply(lambda x: x[0])
positions = name_position.str.split("  ").apply(lambda x: x[1].strip())

print(names[names == 'J.J. Redick'].head(1))
print(names[names == 'Gary Trent Jr.'].head(1))
print(names[names == 'Joe Ingles'].head(1))
print(names[names == 'Frank Mason III'].head(1))

# eliminate special characters in dataframe column names
def clean_player_names(df, suffixes_to_remove):
    """The purpose of this function is to eliminate 
    the special characters in the names column.
    
    It accepts the following parameters:
        1) the dataframe to be cleaned
        2) a list of special characters to be removed
    """
    for suffix in suffixes_to_remove:
        df = df.str.replace(suffix, "", regex=True)
    return df

suffixes_to_remove = ["\."," Jr"," Sr"," III"," II"," IV"]
names = clean_player_names(names, suffixes_to_remove)


1309    J.J. Redick
Name: Player, dtype: object
1248    Gary Trent Jr.
Name: Player, dtype: object
2469    Joe Ingles
Name: Player, dtype: object
431    Frank Mason III
Name: Player, dtype: object


In [ ]:
# eliminate middle names and assign player positions to a new column called Positions
first_name = names.str.split(" ").apply(lambda x: x[0].strip())
last_name = names.str.split(" ").apply(lambda x: x[-1].strip())

df_salary["Names"] = first_name + " " + last_name
df_salary["Positions"] = positions

In [ ]:
# check if '.' and 'Jr' in Names column still exists
print(df_salary['Names'][df_salary['Names'] == "JJ Redick"])
print(df_salary['Names'][df_salary['Names'] == "Gary Trent"])

1309    JJ Redick
1316    JJ Redick
1333    JJ Redick
1354    JJ Redick
1431    JJ Redick
1506    JJ Redick
Name: Names, dtype: object
1248    Gary Trent
1668    Gary Trent
Name: Names, dtype: object


In [ ]:
# extract contract start year, end year, freeagent year data from the Player column and assign them to new columns
start_end_freeagent_yr = split_name_yr.apply(lambda x: x[1])
str_end_free = start_end_freeagent_yr.str.extract(
    "(?P<Start_Year>[\d]*)\-(?P<End_Year>[\d]*)\s\(FA:\s(?P<FreeAgent_Year>.*)\)"
)

# combine str_end_free and df_salary dataframes
df_salary = pd.concat([df_salary, str_end_free], axis=1)
df_salary.head()

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year
0,1,Stephen Curry Point Guard | 2022-2025 (FA: 2026),33,4,"$215,353,664","$53,838,416",NaN,Stephen Curry,Point Guard,2022,2025,2026
1,2,Luka Doncic Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",NaN,Luka Doncic,Point Guard,2022,2026,2027
2,2,Trae Young Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",NaN,Trae Young,Point Guard,2022,2026,2027
3,4,Russell Westbrook Point Guard | 2018-2022 (FA...,28,5,"$206,794,070","$41,358,814",NaN,Russell Westbrook,Point Guard,2018,2022,2023
4,5,LaMelo Ball Point Guard | 2024-2028 (FA: 2029),21,5,"$205,900,000","$41,180,000",NaN,LaMelo Ball,Point Guard,2024,2028,2029


Next, we will proceed to fill the NaN values in the "Sign Bonus" column with '0'. We will then create a function to clean the salary columns (AVV, Value, Sign Bonus) by removing dollar signs and converting their data types to integers.

In [ ]:
# fill NaN values with '0' for Sign Bonus column
df_salary["Sign Bonus"] = df_salary["Sign Bonus"].fillna("0")

In [ ]:
# Create a function to transform string values with dollar sign as numeric integer
def extract_and_clean_numeric(value):
    cleaned_values = value.str.replace("[\$,]", "", regex=True)
    return cleaned_values.astype(int)

In [ ]:
# Create a function create new columns to be assigned with data transformed from extract_and_clean_numeric function
def clean_columns(df, column_lst):
    for i in column_lst:
        df[i + "Clean"] = extract_and_clean_numeric(df[i])

In [ ]:
# extract and clean target columns into numeric
clean_columns(df_salary, ["AAV", "Value", "Sign Bonus"])
df_salary.head()

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean
0,1,Stephen Curry Point Guard | 2022-2025 (FA: 2026),33,4,"$215,353,664","$53,838,416",0,Stephen Curry,Point Guard,2022,2025,2026,53838416,215353664,0
1,2,Luka Doncic Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",0,Luka Doncic,Point Guard,2022,2026,2027,43031940,215159700,0
2,2,Trae Young Point Guard | 2022-2026 (FA: 2027),22,5,"$215,159,700","$43,031,940",0,Trae Young,Point Guard,2022,2026,2027,43031940,215159700,0
3,4,Russell Westbrook Point Guard | 2018-2022 (FA...,28,5,"$206,794,070","$41,358,814",0,Russell Westbrook,Point Guard,2018,2022,2023,41358814,206794070,0
4,5,LaMelo Ball Point Guard | 2024-2028 (FA: 2029),21,5,"$205,900,000","$41,180,000",0,LaMelo Ball,Point Guard,2024,2028,2029,41180000,205900000,0


Let's determine the number of players who have received bonuses. We will then add these bonuses to the total salary and distribute them evenly over the duration of their respective contracts, thereby calculating the annual bonus contribution to their salaries.

In [ ]:
# totally 18 rows with sign bonus
df_salary[['Names','Sign BonusClean']][df_salary["Sign Bonus"] != "0"]

,Names,Sign BonusClean
185,Jarrett Jack,3500000
1235,Malik Beasley,300000
1289,Wesley Matthews,5690000
1354,JJ Redick,500000
1565,Michael Jordan,250000
1689,Zoran Dragic,412500
2432,Jimmy Butler,4600000
2483,Nicolas Batum,1500000
2670,Kostas Papanikolaou,206598
3564,John Henson,4000000


In [ ]:
# add bonus on total salary and allocate bonus to each year's salary
df_salary["AAV+Bonus"] = (
    df_salary["Sign BonusClean"] / df_salary["Yrs"] + df_salary["AAVClean"]
)
df_salary["Value+Bonus"] = df_salary["Sign BonusClean"] + df_salary["ValueClean"]


Next let's check the 'Yrs', 'Start_Year', 'End_Year', 'FreeAgent_Year' columns. 

In [ ]:
print('Any Zero values for Yrs: ', (df_salary["Yrs"] == 0).any())
print('NaN values for Yrs: ', df_salary["Yrs"].isna().any())

Any Zero values for Yrs:  False
NaN values for Yrs:  False


There are no 0 or NaN values in contract year column(Yrs). Let's explore the data in 'Start_Year', 'End_Year', 'FreeAgent_Year' columns

In [ ]:
# convert data type from string to int
df_salary[["Start_Year", "End_Year", "FreeAgent_Year"]] = df_salary[
    ["Start_Year", "End_Year", "FreeAgent_Year"]
].astype(int)

print('shape if any zero values for Start_Year, End_Year, and FreeAgent_Year: ',
    df_salary[
        (df_salary["Start_Year"] == 0)
        | (df_salary["End_Year"] == 0)
        | (df_salary["FreeAgent_Year"] == 0)
    ].shape
)

print('shape of all Start_Year, End_Year, and FreeAgent_Year are zero: ',
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ].shape
)

print(
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ]
)

shape if any zero values for Start_Year, End_Year, and FreeAgent_Year:  (336, 17)
shape of all Start_Year, End_Year, and FreeAgent_Year are zero:  (2, 17)
      Rank                                Player Signed Age  Yrs       Value  \
5010   352    Robert Swift  Center | 0-0 (FA: 0)         -1    4  $7,894,553   
5535   875  Jaleel Roberts  Center | 0-0 (FA: 0)         23    1    $543,471   

             AAV Sign Bonus           Names Positions  Start_Year  End_Year  \
5010  $1,973,638          0    Robert Swift    Center           0         0   
5535    $543,471          0  Jaleel Roberts    Center           0         0   

      FreeAgent_Year  AAVClean  ValueClean  Sign BonusClean  AAV+Bonus  \
5010               0   1973638     7894553                0  1973638.0   
5535               0    543471      543471                0   543471.0   

      Value+Bonus  
5010      7894553  
5535       543471  


It has been identified that 336 rows contain 0 values in either the 'startYear,' 'endYear,' or 'freeAgentYear' columns, and there are 2 rows where all these columns have values of 0. We will create a function to perform data cleaning and populate the appropriate values in these columns.

In [ ]:
# Create a function to populate the appropriate values in these columns: Start_Year, End_Year, FreeAgent_Year 
# We do not perform manipulation when all three variables are 0 or when all three variables are not 0

def fill_value(row):
    '''The purpose of this function is to fill in most of the Start_Year, End_Year, FreeAgent_Year
    that are 0 values'''
    if row["Start_Year"] == 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] != 0:
        row["End_Year"] = row["FreeAgent_Year"] - 1
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
    if row["Start_Year"] == 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] != 0:
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
    if row["Start_Year"] != 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] != 0:
        row["End_Year"] = row["Start_Year"] + row["Yrs"] - 1
    if row["Start_Year"] != 0 and row["End_Year"] == 0 and row["FreeAgent_Year"] == 0:
        row["End_Year"] = row["Start_Year"] + row["Yrs"] - 1
        row["FreeAgent_Year"] = row["End_Year"] + 1
    if row["Start_Year"] == 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] == 0:
        row["Start_Year"] = row["End_Year"] - row["Yrs"] + 1
        row["FreeAgent_Year"] = row["End_Year"] + 1
    if row["Start_Year"] != 0 and row["End_Year"] != 0 and row["FreeAgent_Year"] == 0:
        row["FreeAgent_Year"] = row["End_Year"] + 1
    return row

#apply fill in function for Start_Year, End_Year, FreeAgent_Year to the df_salary dataframe 
df_salary = df_salary.apply(fill_value, axis=1)

Next, we will address the missing values in the "Start_Year," "End_Year," and "FreeAgent_Year" columns. However, it's important to note that we encountered significant inaccuracies in Robert Swift's data within our dataset, making it challenging to rectify. Additionally, we discovered that Jaleel Roberts is a G-League player rather than an NBA player. Consequently, we have made the decision to remove these two data points from our dataset.

In [ ]:
# check Robert Swift and Jaleel Roberts data rows
df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ]



,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean,AAV+Bonus,Value+Bonus
5010,352,Robert Swift Center | 0-0 (FA: 0),-1,4,"$7,894,553","$1,973,638",0,Robert Swift,Center,0,0,0,1973638,7894553,0,1973638.0,7894553
5535,875,Jaleel Roberts Center | 0-0 (FA: 0),23,1,"$543,471","$543,471",0,Jaleel Roberts,Center,0,0,0,543471,543471,0,543471.0,543471


In [ ]:
# drop Robert Swift and Jaleel Roberts data rows
df_salary.drop(
    df_salary[
        (df_salary["Start_Year"] == 0)
        & (df_salary["End_Year"] == 0)
        & (df_salary["FreeAgent_Year"] == 0)
    ].index,
    inplace=True
)

In [ ]:
#function for checking the string length of year
def check_year_length(specific_year):
    '''The purpose of this function is to check if there are any years less than 4 numbers'''
    if len(str(specific_year)) < 4:
        return specific_year
    else:
        return np.nan

#check any year that is incorrectly not a length of 4 numbers
for year in ["Start_Year", "End_Year", "FreeAgent_Year"]:
    series_year_not_accurate = df_salary[year].apply(check_year_length)
    year_index = series_year_not_accurate[series_year_not_accurate.isnull() == False].index
    print(df_salary['Names'].loc[year_index])
    print(series_year_not_accurate[series_year_not_accurate.isnull() == False])



Series([], Name: Names, dtype: object)
Series([], Name: Start_Year, dtype: float64)
593    Raul Neto
Name: Names, dtype: object
593    202.0
Name: End_Year, dtype: float64
4545     Jameel Warney
5201    DeAndre Jordan
Name: Names, dtype: object
4545     20.0
5201    202.0
Name: FreeAgent_Year, dtype: float64


We can notice from the above output that the following 3 players (Raul Neto, Jameel Warney and DeAndre Jordan) have incorrect length of either End_Year or FreeAgent_Year variables.

In [ ]:
#check the 3 names that have incorrect End_Year and FreeAgent_Year so we can fill in
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "Raul Neto"])
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "Jameel Warney"])
print(df_salary[["Names", "Start_Year", "End_Year", "FreeAgent_Year", "AAV", "Value"]][df_salary["Names"] == "DeAndre Jordan"])

         Names  Start_Year  End_Year  FreeAgent_Year         AAV       Value
414  Raul Neto        2018      2019            2020  $2,200,000  $4,400,000
499  Raul Neto        2015      2017            2018    $910,849  $2,732,546
528  Raul Neto        2022      2022            2023  $2,463,490  $2,463,490
593  Raul Neto        2021       202            2022  $2,089,448  $2,089,448
618  Raul Neto        2020      2020            2021  $1,882,867  $1,882,867
646  Raul Neto        2019      2019            2020  $1,737,145  $1,737,145
              Names  Start_Year  End_Year  FreeAgent_Year       AAV     Value
4501  Jameel Warney        2017      2017            2018  $815,615  $815,615
4545  Jameel Warney        2016      2016              20  $543,471  $543,471
               Names  Start_Year  End_Year  FreeAgent_Year          AAV  \
4690  DeAndre Jordan        2015      2018            2019  $21,904,013   
4773  DeAndre Jordan        2011      2014            2015  $10,759,764   
47

In [ ]:
#fill in incorrect year value
df_salary.at[593,'End_Year'] = 2021
df_salary.at[4545, 'FreeAgent_Year'] = 2017
df_salary.at[5201, 'FreeAgent_Year'] = 2022

Next, we will create a 'Year_List' column. Our goal is to expand the data in this 'Year_List' by breaking down contracts spanning multiple years into individual yearly contracts. This will facilitate the merging of the player statistic and salary dataframe on season years.

In [ ]:
# make the year_list so we can explode it 
start_years = df_salary["Start_Year"].values
end_years = df_salary["End_Year"].values
df_salary["Year_List"] = [
    np.arange(start, end + 1) for start, end in zip(start_years, end_years)
]

In [ ]:
#explode the Year_List column for each row to include each year of the contract
df_salary_exploded = df_salary.explode("Year_List")


In [ ]:
# check any 0 value in column Year_List
df_salary_exploded[df_salary_exploded["Year_List"] == 0]

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean,AAV+Bonus,Value+Bonus,Year_List


In [ ]:
# check any nan value in column Year_List
df_salary_exploded[df_salary_exploded["Year_List"].isna()]

,Rank,Player,Signed Age,Yrs,Value,AAV,Sign Bonus,Names,Positions,Start_Year,End_Year,FreeAgent_Year,AAVClean,ValueClean,Sign BonusClean,AAV+Bonus,Value+Bonus,Year_List


We have now successfully manipulated and cleaned the year columns. The next step involves merging the salary data (df_salary_exploded) and the statistics data (player_statistics_country) based on player names and years. However, before proceeding with the merge, it is essential to check for any discrepancies or mismatches between the player names in the two datasets. 

In [ ]:
names_set1 = set(df_salary_exploded['Names'])
names_set2 = set(player_statistics_country['PLAYER_NAME'])

# Players present in the first dataset but not in the second dataset
in_df1_not_in_df2 = names_set1 - names_set2

# Players present in the second dataset but not in the first dataset
in_df2_not_in_df1 = names_set2 - names_set1

# Print the discrepancies
print("Players in salary but not in stats:")
print(in_df1_not_in_df2)

print("\nPlayers in stats but not in salary:")
print(in_df2_not_in_df1)

Players in salary but not in stats:
{'Ben Sheppard', 'Melo Trimble', 'Christian Watford', 'Jordan Henriquez', 'Mark Ogden', 'Shawn Dawson', 'Brady Heslip', 'Shizz Alston', 'BJ Young', 'Matthew Hurt', 'Bryce Hamilton', 'Robert Vaden', 'Brock Motum', "Hamady N'Diaye", 'Paul Eboua', 'Rick Jackson', 'Matur Maker', 'Max Heidegger', 'Jeff Taylor', 'Michael Eric', 'Nikola Jovanovic', 'Brandon Rachal', 'Nate Sestina', 'Christian Vital', 'Kyle Casey', 'Mustapha Farrakhan', 'Fuquan Edwin', 'Rayan Rupert', 'Vashil Fernandez', 'Dmytro Skapintsev', 'Kleon Penn', 'George Conditt', 'Stefhon Hannah', 'Jordan Vandenberg', 'Aamir Simms', 'Shawn Jones', 'Sheldon McClellan', 'Edgar Sosa', 'Tony Gaffney', 'Jordan Railey', 'Eric Griffin', 'Jake Anderson', 'Goran Suton', 'Darryl Morsell', 'Zach Smith', 'Joseph Young', 'Ronald Roberts', 'Bilal Coulibaly', 'DeJaun Blair', 'Alex Antetokounmpo', "Maurice N'dour", 'Quinton Rose', 'Jacob Toppin', 'CJ Aiken', 'Oscar Bellfield', 'Matt Janning', 'Dan Nwaelele', 'Trev

In [ ]:
len(in_df1_not_in_df2)

471

We expect the salary dataset to be incomplete and to not have values seen in the statistics dataset from nba.com because sportrac only contains at most the top 2000 salaries for each position and is not the official basketball website. It is therefore prudent to ignore player names in statistics dataset that are not in salary (in_df2_not_in_df1). On the other hand, we expect most of the players in the salary dataset to be in the statistics nba.com dataset since it is their official website and should be complete. So it is surprising that there are so many names in the salary dataset that are not in the nba.com dataset (in_df1_not_in_df2). We will have to investigate further by looking at individual instances of the players' profiles to determine why those names are not in the nba.com website. To do so, lets first save the missing_names to a csv and then research.

In [ ]:
missing_names = pd.DataFrame(in_df1_not_in_df2, columns = ['missing_names']).sort_values(by = 'missing_names').to_csv('Name_Mismatch.csv', index = False)

After researching through wikipedia.com and the statistics page on nba.com, we have found the reasons for all the missing data in the missing_names.csv file created above. We noticed that there is either: a) a mismatch in the names between salary and statistics dataframes or b) they never played a regular NBA game yet even though they may have salary contracts. We updated the missing_names.csv file with a 'mismatch' and 'reason' columns corresponding to the aforementioned reasons and will now upload the newly created missing_names_filled.csv file.

In [ ]:
#read filled out names with 'mismatch' or an alternate 'reason' on salary dataset
name_mismatch_filled = pd.read_csv('Name_Mismatch_Filled.csv')

name_mismatch_filled.head()

,names,mismatch,reason
0,AJ Reeves,NaN,G-league
1,Aamir Simms,NaN,LBA
2,Aaron Craft,NaN,G-league
3,Abdul Gaddy,NaN,G-league
4,Akil Mitchell,NaN,G-league


In [ ]:
#see all the names that had mismatches
name_fix = name_mismatch_filled[name_mismatch_filled['reason'].isnull()][['names','mismatch']]
name_fix

,names,mismatch
31,Brandon Dawson,Branden Dawson
52,Cameron Thomas,Cam Thomas
68,Christapher Johnson,Chris Johnson
95,DeJaun Blair,DeJuan Blair
100,Dennis Schröder,Dennis Schroder
136,Garrett Siler,Garret Siler
146,Hamady N'Diaye,Hamady Ndiaye
149,Herb Jones,Herbert Jones
157,Ishmael Smith,Ish Smith
158,Ishmail Wainright,Ish Wainright


In [ ]:
#check all the mismatch names are accounted for in the statistics dataframe
mismatch_names = set(name_fix['mismatch'])
names_in_stats = set(player_statistics_country['PLAYER_NAME'])
mismatch_names-names_in_stats

set()

We have identified all the mismatched names, and our next step is to replace these mismatched names in the salary data with the official NBA player names

In [ ]:
#make a dictionary of names and their replacements
name_to_replace_dict = dict(zip(name_fix['names'], name_fix['mismatch']))

#replace mismatched names of salary dataset with the official NBA player name
df_salary_exploded['Names'].replace(name_to_replace_dict, inplace = True)

Let's look at the number of names left that were not mismatches

In [ ]:
names_set1 = set(df_salary_exploded['Names'])
names_set2 = set(player_statistics_country['PLAYER_NAME'])

# Players present in the first dataset but not in the second dataset
in_df1_not_in_df2 = names_set1 - names_set2

# Players present in the second dataset but not in the first dataset
in_df2_not_in_df1 = names_set2 - names_set1

# Print the discrepancies
print("Players in salary but not in stats:")
print(in_df1_not_in_df2)

print("\nPlayers in stats but not in salary:")
print(in_df2_not_in_df1)

Players in salary but not in stats:
{'Ben Sheppard', 'Melo Trimble', 'Christian Watford', 'Jordan Henriquez', 'Mark Ogden', 'Shawn Dawson', 'Brady Heslip', 'Shizz Alston', 'BJ Young', 'Matthew Hurt', 'Bryce Hamilton', 'Robert Vaden', 'Brock Motum', 'Paul Eboua', 'Rick Jackson', 'Matur Maker', 'Max Heidegger', 'Michael Eric', 'Nikola Jovanovic', 'Brandon Rachal', 'Nate Sestina', 'Christian Vital', 'Kyle Casey', 'Mustapha Farrakhan', 'Fuquan Edwin', 'Rayan Rupert', 'Vashil Fernandez', 'Dmytro Skapintsev', 'Kleon Penn', 'George Conditt', 'Stefhon Hannah', 'Jordan Vandenberg', 'Aamir Simms', 'Shawn Jones', 'Edgar Sosa', 'Tony Gaffney', 'Jordan Railey', 'Eric Griffin', 'Jake Anderson', 'Goran Suton', 'Darryl Morsell', 'Zach Smith', 'Ronald Roberts', 'Bilal Coulibaly', 'Alex Antetokounmpo', "Maurice N'dour", 'Quinton Rose', 'Jacob Toppin', 'CJ Aiken', 'Oscar Bellfield', 'Matt Janning', 'Dan Nwaelele', 'Tomislav Zubcic', 'LJ Figueroa', 'Remi Yusuf', 'Greg Somogyi', 'John Petty', 'Maxwell Lewi

In [ ]:
#number of players that supposedly did not play in the nba (ever or yet)
len(in_df1_not_in_df2)

428

During the merging of all the datasets in the next section, these 428 player names will be automatically dropped by the join statement.

In [ ]:
#check if replacement worked 
names_not_relevant = set(name_mismatch_filled['names'][name_mismatch_filled['mismatch'].isnull()])
set(df_salary_exploded['Names'])-names_in_stats-names_not_relevant


set()

The empty set indicates that all the mismatched names were properly updated. Finally, we will eliminate or drop those columns that will not be utilized in our future analysis

In [ ]:
#list of columns
df_salary_exploded.columns

Index(['Rank', 'Player', 'Signed Age', 'Yrs', 'Value', 'AAV', 'Sign Bonus',
       'Names', 'Positions', 'Start_Year', 'End_Year', 'FreeAgent_Year',
       'AAVClean', 'ValueClean', 'Sign BonusClean', 'AAV+Bonus', 'Value+Bonus',
       'Year_List'],
      dtype='object')

In [ ]:

#dropping unnecessary columns
df_salary_exploded.drop(
    columns = [
        "Signed Age",
        "Value",
        "AAV",
        "Sign Bonus",
        "Player",
        "Start_Year",
        "End_Year",
        "Rank",
        "Yrs",
        "FreeAgent_Year",
        "Sign BonusClean",
        "AAVClean",
        "ValueClean",
        "Value+Bonus"

    ],
    inplace = True,
)


### 3. Merge combined Primary and Secondary 'Statistics and Country Dataset' with the Tertiary 'Salary Dataset'

In [ ]:
#look at the years of season_id range and Year_List range 
print('all years in player_statistics_country dataset: ', pd.unique(player_statistics_country["season_id"]))
print('all years in tertiary salary dataset: ', pd.unique(df_salary_exploded["Year_List"]))

# Merge
df_statistics_salary = player_statistics_country.merge(
    df_salary_exploded,
    left_on=["PLAYER_NAME", "season_id"],
    right_on=["Names", "Year_List"],
)



all years in player_statistics_country dataset:  [1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009
 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
all years in tertiary salary dataset:  [2022 2023 2024 2025 2026 2018 2019 2020 2021 2027 2028 2017 2016 2013
 2014 2015 2003 2004 2005 2006 2007 2008 2012 1999 2000 2001 2002 1996
 1997 1998 1994 1995 2009 2010 2011 1993 1984 1985 1986 1987 1988 1989
 1990 1991 1992 1979 1980 1981 1982 1983]


We should also check if the instances of names and years present in the salary dataset are not in the statistics dataset. While all the names are accounted for previously for the salary and statistics due to mismatches or players never playing NBA games, we should also further inspect year instances.

In [ ]:
#list of names and years in the salary dataset
full_names = df_salary_exploded["Names"]
full_years = df_salary_exploded["Year_List"]

#initialize list for name, year missing in statistics dataset
lst_name_year_missing = []

#append list for missing names and years
for name, year in zip(full_names, full_years):
    if name in list(df_statistics_salary.loc[:, 'Names']) and len(df_statistics_salary['Year_List'][(df_statistics_salary['Year_List'] == year) & (df_statistics_salary['Names'] == name)]) > 0:
        continue
    else:
        if year < 2023 and year > 1995 and name not in names_not_relevant:
            lst_name_year_missing.append([name, year])

#print list
print(lst_name_year_missing)



[['Ben Simmons', 2021], ['John Wall', 2019], ['John Wall', 2021], ['Jamal Murray', 2021], ['Derrick Rose', 2012], ['Lonzo Ball', 2022], ['Eric Bledsoe', 2022], ['Brandon Knight', 2017], ['Baron Davis', 2012], ['Charlie Bell', 2011], ['Marko Jaric', 2009], ['Marko Jaric', 2010], ['Jamaal Tinsley', 2008], ['Jamaal Tinsley', 2010], ['Antonio Daniels', 2009], ['Steve Nash', 2014], ['Ben Simmons', 2016], ['Speedy Claxton', 2007], ['Speedy Claxton', 2009], ['Shaun Livingston', 2019], ['DJ Augustin', 2022], ['Rodney Stuckey', 2017], ['Dante Exum', 2015], ['Damon Jones', 2009], ['Damon Jones', 2010], ['Damon Jones', 2011], ['Chris Duhon', 2013], ['CJ Watson', 2017], ['Shaun Livingston', 2007], ['Jay Williams', 2003], ['Jay Williams', 2004], ['Kendrick Nunn', 2021], ['Tony Parker', 2019], ['Trey Burke', 2022], ['TJ Ford', 2004], ['Jason Kidd', 2013], ['Jason Kidd', 2014], ['Wade Baldwin', 2019], ['Dante Exum', 2021], ['Dante Exum', 2022], ['Kendall Marshall', 2016], ['Kendall Marshall', 2017], 

In [ ]:


#save list of names not in stats dataframe
save_not_relevant_names = pd.DataFrame(lst_name_year_missing, columns = ['Name', 'Year']).sort_values(by='Name').to_csv('Missing_Not_Relevant_Names_Stats.csv', index = False)

There are clearly still a lot of unique instances (name, year) in the combined df_statistics_salary that are not in the salary dataset. This may seem odd, since we replaced all the mismatch values but it turns out that these single name, year are the result of the players having a salary contract for that year but not playing in the NBA or having contracts that are not NBA related. 

In [ ]:
df_final_statistics_salary = df_statistics_salary.reset_index()
df_final_statistics_salary.drop(columns = ["index"], inplace = True)
df_final_statistics_salary.to_csv("Final_Stats_Salary.csv", index = False)

We have merged the datasets and saved them to csv - lets do a final check of the dataset to make sure it has mostly non-negative values in the columns and it makes sense.

In [ ]:
#check to see if values make sense, their type, and that they are generally  negative 
def makes_sense(df):
    '''The purpose of this function is to check if any values in the 
    final merged dataset are negative'''
    for column in df.columns:
        if df[column].dtypes == int or df[column].dtypes == float:
            print(
                'Negative Values Count for '+ column + ': ', 
                df[column][df[column] < 0].count(), 
            )
            print(
                'NaN values for ' + column + ': ', 
                df[column][df[column].isnull()].count(),
                end = '\n\n'
            )
        else:
            print(
                column + ' is not numerical and is type: ', 
                df[column].dtypes
            )
            print(
                'NaN values for ' + column + ': ', 
                df[column][df[column].isnull()].count(),
                end = '\n\n'
            )

#use greater than zero function to check df_final_statistics_salary
makes_sense(df_final_statistics_salary)


Negative Values Count for PLAYER_ID:  0
NaN values for PLAYER_ID:  0

PLAYER_NAME is not numerical and is type:  object
NaN values for PLAYER_NAME:  0

NICKNAME is not numerical and is type:  object
NaN values for NICKNAME:  0

Negative Values Count for TEAM_ID:  0
NaN values for TEAM_ID:  0

TEAM_ABBREVIATION is not numerical and is type:  object
NaN values for TEAM_ABBREVIATION:  0

Negative Values Count for AGE:  0
NaN values for AGE:  0

Negative Values Count for GP:  0
NaN values for GP:  0

Negative Values Count for W:  0
NaN values for W:  0

Negative Values Count for L:  0
NaN values for L:  0

Negative Values Count for W_PCT:  0
NaN values for W_PCT:  0

Negative Values Count for MIN:  0
NaN values for MIN:  0

Negative Values Count for FGM:  0
NaN values for FGM:  0

Negative Values Count for FGA:  0
NaN values for FGA:  0

Negative Values Count for FG_PCT:  0
NaN values for FG_PCT:  0

Negative Values Count for FG3M:  0
NaN values for FG3M:  0

Negative Values Count for FG3A

We can see that the values do make sense, there are <B>no NaN values</B> in columns that are numeric and string columns are all object types. There are a few negative columns such as in ratings, PIE, or plus-minus column but those seem to make sense as those statistics should have negative values in it. 

This concludes our data manipulation and curation journey, we will next investigate insights into the dataset through our exploratory analysis.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=0b855501-6f2c-4764-816d-be07593df653' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>